### ISSUE TITLE
Unable to build a hello world app

### ISSUE THREAD

**Issue by Scellow** [ngrebenshikov/jive#84]
Hello

I tried to build a hello world, both using openfl

I tested target Mac and Neko, both fail

# Haxe
```
Haxe Compiler 3.2.0 
OpenFL Command-Line Tools (3.1.4-LO4OHo)
Lime Command-Line Tools (2.5.0)
```

# Project:

```xml
<?xml version="1.0" encoding="utf-8"?>
<project>
	
	<meta title="Twitcher" package="com.sample.twitcher" version="1.0.0" company="Company Name" />
	<app main="Main" path="Export" file="Twitcher" />

	<source path="src" />

	<haxelib name="openfl"/>
    <haxelib name="jive"/>
    <haxelib name="bindx"/>

	<assets path="assets" />
	
</project>
```

# Source

```haxe
package ;

import openfl.display.Sprite;
import openfl.Lib;

import org.aswing.UIManager;
import org.aswing.AsWingManager;
import jive.plaf.flat.FlatLookAndFeel;

class Main extends Sprite
{
    public function new()
    {
        super();

        AsWingManager.initAsStandard(Lib.current);
        UIManager.setLookAndFeel(new FlatLookAndFeel());
    }
}
```

# Neko output:

https://gist.github.com/Scellow/14ba79e26da30aa3f9ef

# Mac output:

https://gist.github.com/Scellow/ad0f50057a943613482f

**Comment by ngrebenshikov** [comment]
Hi
Now I'm investigating why the neko doesn't work but the mac version is compiled correctly regarding your log. I can try to run it. It seems that Idea interpreted the openfl compiler output as errors.

**Comment by ngrebenshikov** [comment]
About neko. Could you write what size of your neko binary file is? It's placed in bin/mac/neko/obj

It seems that the problem because of the large size of binary. Neko can work only with binaries less than 1Mb. https://github.com/HaxeFoundation/neko/commit/33a9a460eb9ec8ae64ccb003ac7077a13561619c

**Comment by Scellow** [comment]
You are right, the mac build has actually been built correctly! Thanks

The neko binary filesize is 2mb
